services:
  web:
    image: ghcr.io/lordimac/kyocera_reports:latest
    ports:
      - "5000:5000"
    environment:
      - POP3_SERVER=${POP3_SERVER}
      - POP3_PORT=${POP3_PORT}
      - POP3_USERNAME=${POP3_USERNAME}
      - POP3_PASSWORD=${POP3_PASSWORD}
    volumes:
      - ./data:/app/data