services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///app/kyocera_reports.db
      - POP3_SERVER=${POP3_SERVER}
      - POP3_PORT=${POP3_PORT}
      - POP3_USERNAME=${POP3_USERNAME}
      - POP3_PASSWORD=${POP3_PASSWORD}
    volumes:
      - .:/app